In [8]:
#dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#file path
csv_path = "../Resources/improvrating.csv"
improvrating_df = pd.read_csv(csv_path)
improvrating_df.head(10)

,District Number,District Name,School Number,School Name,English Language Arts Learning Gains,Mathematics Learning Gains,Total Points Earned,Total Components,Percent of Total Possible Points,Percent Tested,...,Improvement Rating 2010,Improvement Rating 2009,Improvement Rating 2008,Charter School,Alternative/ESE Center School,School Type,Title I,Percent of Minority Students,Percent of Economically Disadvantaged Students,Was the aggregate rule used?
0,1,ALACHUA,81,SIDNEY LANIER CENTER,16.0,22.0,38.0,2.0,19.0,93.0,...,NaN,NaN,NaN,NO,A,4,YES,69.9,100.0,NaN
1,1,ALACHUA,82,HOSPITAL HOMEBOUND,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NO,E,4,NO,50.0,30.0,Y
2,1,ALACHUA,955,"THE EINSTEIN SCHOOL, INC.",35.0,44.0,79.0,2.0,40.0,100.0,...,NaN,NaN,NaN,YES,A,4,NO,54.6,89.8,NaN
3,1,ALACHUA,991,SIATECH AT GAINESVILLE,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,YES,A,3,YES,74.3,96.4,NaN
4,1,ALACHUA,1003,NORTH CENTRAL FLORIDA PUBLIC CHARTER SCHOOL,30.0,52.0,82.0,2.0,41.0,89.0,...,NaN,NaN,NaN,YES,A,4,YES,82.3,100.0,NaN
5,3,BAY,241,ST. ANDREW SCHOOL,17.0,25.0,42.0,2.0,21.0,99.0,...,NaN,NaN,NaN,NO,E,1,YES,53.9,100.0,NaN
6,3,BAY,281,MARGARET K. LEWIS IN MILLVILLE,41.0,40.0,81.0,2.0,41.0,98.0,...,NaN,NaN,NaN,NO,E,4,YES,31.4,100.0,NaN
7,3,BAY,531,NEW HORIZONS LEARNING CENTER,44.0,28.0,72.0,2.0,36.0,92.0,...,NaN,NaN,NaN,NO,E,4,YES,38.3,80.7,NaN
8,3,BAY,581,ROSENWALD HIGH SCHOOL,27.0,52.0,79.0,2.0,40.0,81.0,...,DECLINING,NaN,NaN,NO,A,3,YES,60.9,88.4,NaN
9,3,BAY,591,C C WASHINGTON ACADEMY,26.0,31.0,57.0,2.0,29.0,94.0,...,NaN,NaN,NaN,NO,A,2,YES,47.3,90.7,NaN

In [9]:
#identify columns names used in the data
improvrating_df.columns

Index(['District Number', 'District Name', 'School Number', 'School Name',
       'English Language Arts Learning Gains', 'Mathematics Learning Gains',
       'Total Points Earned', 'Total Components',
       'Percent of Total Possible Points', 'Percent Tested',
       'School Improvement Rating 2019', 'Improvement Rating 2018',
       'Improvement Rating 2017', 'Improvement Rating 2016',
       'Improvement Rating 2014', 'Improvement Rating 2013',
       'Improvement Rating 2012', 'Improvement Rating 2011',
       'Improvement Rating 2010', 'Improvement Rating 2009',
       'Improvement Rating 2008', 'Charter School',
       'Alternative/ESE Center School', 'School Type', 'Title I',
       'Percent of Minority Students',
       'Percent of Economically Disadvantaged Students',
       'Was the aggregate rule used?'],
      dtype='object')

In [10]:
#remove some columns from the data 
improvrating_reduced_df = improvrating_df.loc[:, ['District Number', 'District Name', 'School Number', 'School Name',
       'English Language Arts Learning Gains', 'Mathematics Learning Gains',
       'Total Points Earned', 'Total Components',
       'Percent of Total Possible Points', 'Percent Tested',
       'School Improvement Rating 2019', 'Improvement Rating 2018',
       'Improvement Rating 2017', 'Improvement Rating 2016', 'School Type',
       'Percent of Minority Students',
       'Percent of Economically Disadvantaged Students']]
improvrating_reduced_df.head(10)

,District Number,District Name,School Number,School Name,English Language Arts Learning Gains,Mathematics Learning Gains,Total Points Earned,Total Components,Percent of Total Possible Points,Percent Tested,School Improvement Rating 2019,Improvement Rating 2018,Improvement Rating 2017,Improvement Rating 2016,School Type,Percent of Minority Students,Percent of Economically Disadvantaged Students
0,1,ALACHUA,81,SIDNEY LANIER CENTER,16.0,22.0,38.0,2.0,19.0,93.0,UNSATISFACTORY,UNSATISFACTORY,MAINTAINING,NaN,4,69.9,100.0
1,1,ALACHUA,82,HOSPITAL HOMEBOUND,NaN,NaN,NaN,NaN,NaN,NaN,I,NaN,NaN,NaN,4,50.0,30.0
2,1,ALACHUA,955,"THE EINSTEIN SCHOOL, INC.",35.0,44.0,79.0,2.0,40.0,100.0,MAINTAINING,MAINTAINING,MAINTAINING,MAINTAINING,4,54.6,89.8
3,1,ALACHUA,991,SIATECH AT GAINESVILLE,NaN,NaN,NaN,NaN,NaN,NaN,I,MAINTAINING,MAINTAINING,NaN,3,74.3,96.4
4,1,ALACHUA,1003,NORTH CENTRAL FLORIDA PUBLIC CHARTER SCHOOL,30.0,52.0,82.0,2.0,41.0,89.0,MAINTAINING,MAINTAINING,MAINTAINING,NaN,4,82.3,100.0
5,3,BAY,241,ST. ANDREW SCHOOL,17.0,25.0,42.0,2.0,21.0,99.0,UNSATISFACTORY,MAINTAINING,MAINTAINING,MAINTAINING,1,53.9,100.0
6,3,BAY,281,MARGARET K. LEWIS IN MILLVILLE,41.0,40.0,81.0,2.0,41.0,98.0,MAINTAINING,COMMENDABLE,NaN,NaN,4,31.4,100.0
7,3,BAY,531,NEW HORIZONS LEARNING CENTER,44.0,28.0,72.0,2.0,36.0,92.0,MAINTAINING,UNSATISFACTORY,MAINTAINING,MAINTAINING,4,38.3,80.7
8,3,BAY,581,ROSENWALD HIGH SCHOOL,27.0,52.0,79.0,2.0,40.0,81.0,MAINTAINING,MAINTAINING,MAINTAINING,UNSATISFACTORY,3,60.9,88.4
9,3,BAY,591,C C WASHINGTON ACADEMY,26.0,31.0,57.0,2.0,29.0,94.0,MAINTAINING,MAINTAINING,MAINTAINING,UNSATISFACTORY,2,47.3,90.7

In [11]:
#columns to use in the table below 
columns = ['District Name', 'School Number', 'School Name',
       'English Language Arts Learning Gains', 'Mathematics Learning Gains',
       'Total Points Earned',
       'Percent of Total Possible Points', 'Percent Tested',
       'School Improvement Rating 2019', 'Improvement Rating 2018',
       'Improvement Rating 2017', 'Improvement Rating 2016',
       'Percent of Minority Students',
       'Percent of Economically Disadvantaged Students'
]
#create a new DF for non Traffic related crimes
hillsschools_df = improvrating_reduced_df.loc[improvrating_reduced_df["District Name"] == "HILLSBOROUGH", columns]
hillsschools_df.head(10)

,District Name,School Number,School Name,English Language Arts Learning Gains,Mathematics Learning Gains,Total Points Earned,Percent of Total Possible Points,Percent Tested,School Improvement Rating 2019,Improvement Rating 2018,Improvement Rating 2017,Improvement Rating 2016,Percent of Minority Students,Percent of Economically Disadvantaged Students
96,HILLSBOROUGH,63,CARVER EXCEPTIONAL CENTER,22.0,31.0,53.0,27.0,97.0,MAINTAINING,MAINTAINING,MAINTAINING,MAINTAINING,84.0,96.0
97,HILLSBOROUGH,363,WATERS CAREER CENTER,38.0,48.0,86.0,43.0,79.0,MAINTAINING,MAINTAINING,COMMENDABLE,MAINTAINING,93.8,94.5
98,HILLSBOROUGH,371,SIMMONS CAREER CENTER,52.0,71.0,123.0,62.0,92.0,COMMENDABLE,COMMENDABLE,COMMENDABLE,MAINTAINING,66.0,86.4
99,HILLSBOROUGH,1202,WILLIS PETERS EXCEPTIONAL CENTER,24.0,9.0,33.0,17.0,97.0,UNSATISFACTORY,MAINTAINING,NaN,NaN,57.1,75.3
100,HILLSBOROUGH,2541,LOPEZ EXCEPTIONAL STUDENT EDUCATION CENTER,18.0,25.0,43.0,22.0,100.0,UNSATISFACTORY,MAINTAINING,NaN,NaN,59.7,82.3
101,HILLSBOROUGH,2972,MENDEZ EXCEPTIONAL CENTER,41.0,19.0,60.0,30.0,90.0,MAINTAINING,MAINTAINING,NaN,NaN,80.0,92.9
102,HILLSBOROUGH,3782,LAVOY EXCEPTIONAL CENTER,19.0,14.0,33.0,17.0,96.0,UNSATISFACTORY,MAINTAINING,NaN,NaN,72.7,71.8
103,HILLSBOROUGH,4002,SIMMONS EXCEPTIONAL CENTER,50.0,18.0,68.0,34.0,91.0,MAINTAINING,UNSATISFACTORY,MAINTAINING,MAINTAINING,52.9,83.3
104,HILLSBOROUGH,4154,SOUTH COUNTY CAREER CENTER,47.0,52.0,99.0,50.0,93.0,COMMENDABLE,MAINTAINING,MAINTAINING,MAINTAINING,71.1,80.6
105,HILLSBOROUGH,4155,BOWERS-WHITLEY CAREER CENTER,41.0,57.0,98.0,49.0,94.0,MAINTAINING,COMMENDABLE,MAINTAINING,NaN,79.5,89.0