In [13]:
import pandas as pd

In [14]:
# Read .csv file from Florida Department of Education
file = "./SchoolGrades19_clean.csv"
school_grades = pd.read_csv(file)
pd.set_option('display.max_columns', None)

# Drop all but Hillsborough County schools
index_names = school_grades[(school_grades['District Name'] != "HILLSBOROUGH")].index 
school_grades.drop(index_names, inplace = True)

school_grades.head()

,District Number,District Name,School Number,School Name,English Language Arts Achievement,English Language Arts Learning Gains,English Language Arts Learning Gains of the Lowest 25%,Mathematics Achievement,Mathematics Learning Gains,Mathematics Learning Gains of the Lowest 25%,Science Achievement,Social Studies Achievement,Middle School Acceleration,Graduation Rate 2017-18,College and Career Acceleration 2017-18,Total Points Earned,Total Components,Percent of Total Possible Points,Percent Tested,Grade 2019,Grade 2018,Grade 2017,Grade 2016,Informational Baseline Grade 2015,Grade 2014,Grade 2013,Grade 2012,Grade 2011,Grade 2010,Grade 2009,Grade 2008,Grade 2007,Grade 2006,Grade 2005,Grade 2004,Grade 2003,Grade 2002,Grade 2001,Grade 2000,Grade 1999,Was the collocated rule used?,Collocated Number,Charter School,Title I,Alternative/ESE Center School,School Type,Percent of Minority Students,Percent of Economically Disadvantaged Students
1418,29,HILLSBOROUGH,5,WARREN HOPE DAWSON ELEMENTARY,50,53,54,40,31,34,41,0,0,0,0,303,7,43,99,C,C,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,N,0.0,NO,NO,N,1,50.6,48.3
1419,29,HILLSBOROUGH,41,ADAMS MIDDLE SCHOOL,28,34,33,33,44,40,26,31,66,0,0,335,9,37,99,D,C,C,C,C,C,C,B,A,A,A,A,A,A,B,B,A,A,A,C,C,N,0.0,NO,YES,N,2,87.5,91.6
1420,29,HILLSBOROUGH,42,FOREST HILLS ELEMENTARY SCHOOL,34,56,60,37,56,62,33,0,0,0,0,338,7,48,100,C,D,D,F,F,D,C,C,C,C,B,C,B,B,C,B,B,B,C,C,C,N,0.0,NO,YES,N,1,85.6,94.6
1421,29,HILLSBOROUGH,43,SPOTO HIGH SCHOOL,30,34,28,31,41,43,58,57,0,88,36,446,10,45,97,C,C,C,C,C,C,B,B,A,D,D,C,D,0,0,0,0,0,0,0,0,N,0.0,NO,YES,N,3,84.2,75.8
1422,29,HILLSBOROUGH,51,SHEEHY ELEMENTARY SCHOOL,32,58,67,39,63,54,38,0,0,0,0,351,7,50,100,C,D,D,D,F,D,F,D,C,C,B,C,B,C,C,0,0,0,0,0,0,N,0.0,NO,YES,N,1,97.4,98

In [15]:
school_grades.count()

District Number                                           260
District Name                                             260
School Number                                             260
School Name                                               260
English Language Arts Achievement                         260
English Language Arts Learning Gains                      260
English Language Arts Learning Gains of the Lowest 25%    260
Mathematics Achievement                                   260
Mathematics Learning Gains                                260
Mathematics Learning Gains of the Lowest 25%              260
Science Achievement                                       260
Social Studies Achievement                                260
Middle School Acceleration                                260
Graduation Rate 2017-18                                   260
College and Career Acceleration 2017-18                   260
Total Points Earned                                       260
Total Components                                          260
Percent of Total Possible Points                          260
Percent Tested                                            260
Grade 2019                                                260
Grade 2018                                                260
Grade 2017                                                260
Grade 2016                                                260
Informational Baseline Grade 2015                         260
Grade 2014                                                260
Grade 2013                                                260
Grade 2012                                                260
Grade 2011                                                260
Grade 2010                                                260
Grade 2009                                                260
Grade 2008                                                260
Grade 2007                                                260
Grade 2006                                                260
Grade 2005                                                260
Grade 2004                                                260
Grade 2003                                                260
Grade 2002                                                260
Grade 2001                                                260
Grade 2000                                                260
Grade 1999                                                260
Was the collocated rule used?                             260
Collocated Number                                         260
Charter School                                            260
Title I                                                   260
Alternative/ESE Center School                             260
School Type                                               260
Percent of Minority Students                              260
Percent of Economically Disadvantaged Students            260
dtype: int64

In [17]:
# Remove Callocated Rule columns as the rule was not used in this dataset
school_grades_basic = school_grades.loc[:, ["District Number", "District Name", "School Number", "School Name", 
                                            "Graduation Rate 2017-18", "College and Career Acceleration 2017-18", 
                                            "Total Points Earned", "Total Components", "Percent of Total Possible Points", 
                                            "Percent Tested", "Grade 2019", "Grade 2018", "Grade 2017", "Grade 2016", 
                                            "Informational Baseline Grade 2015", "Charter School", "Title I", 
                                            "Alternative/ESE Center School", "School Type", "Percent of Minority Students", 
                                            "Percent of Economically Disadvantaged Students"]]
# Drop schools with missing grade data from 2015
indexNames = school_grades_basic[school_grades_basic['Informational Baseline Grade 2015'] == '0'].index
 
# Delete these row indexes from dataFrame
school_grades_basic = school_grades_basic.drop(indexNames)
school_grades_basic

,District Number,District Name,School Number,School Name,Graduation Rate 2017-18,College and Career Acceleration 2017-18,Total Points Earned,Total Components,Percent of Total Possible Points,Percent Tested,Grade 2019,Grade 2018,Grade 2017,Grade 2016,Informational Baseline Grade 2015,Charter School,Title I,Alternative/ESE Center School,School Type,Percent of Minority Students,Percent of Economically Disadvantaged Students
1419,29,HILLSBOROUGH,41,ADAMS MIDDLE SCHOOL,0,0,335,9,37,99,D,C,C,C,C,NO,YES,N,2,87.5,91.6
1420,29,HILLSBOROUGH,42,FOREST HILLS ELEMENTARY SCHOOL,0,0,338,7,48,100,C,D,D,F,F,NO,YES,N,1,85.6,94.6
1421,29,HILLSBOROUGH,43,SPOTO HIGH SCHOOL,88,36,446,10,45,97,C,C,C,C,C,NO,YES,N,3,84.2,75.8
1422,29,HILLSBOROUGH,51,SHEEHY ELEMENTARY SCHOOL,0,0,351,7,50,100,C,D,D,D,F,NO,YES,N,1,97.4,98
1423,29,HILLSBOROUGH,52,GIUNTA MIDDLE SCHOOL,0,0,341,9,38,99,D,D,C,C,C,NO,YES,N,2,83.7,87.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1660,29,HILLSBOROUGH,6669,RCMA LEADERSHIP ACADEMY,0,0,549,9,61,100,B,B,C,C,C,YES,YES,N,2,99.1,100
1661,29,HILLSBOROUGH,6671,HILLSBOROUGH ACADEMY OF MATH AND SCIENCE,0,0,611,9,68,100,A,B,A,B,A,YES,NO,N,4,76.2,52.6
1662,29,HILLSBOROUGH,7023,HILLSBOROUGH VIRTUAL SCHOOL,88,47,719,11,65,99,A,B,A,A,B,NO,NO,N,4,47.9,23.8
1663,29,HILLSBOROUGH,7675,BRIDGEPREP ACADEMY OF TAMPA,0,0,511,9,57,99,B,B,C,D,F,YES,YES,N,4,77.1,79.5
1664,29,HILLSBOROUGH,7680,VILLAGE OF EXCELLENCE ACADEMY MIDDLE SCHOOL,0,0,346,9,38,98,D,C,B,D,F,YES,YES,N,2,99.1,82.1

In [ ]:
school_grades.head()